version: 0.2
phases:
  install:
    runtime-versions:
      docker: 19
      ruby: 2.6
    commands:
      - echo "cd into $CODEBUILD_SRC_DIR/backend-flask"
      - cd $CODEBUILD_SRC_DIR/backend-flask
      - "aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $IMAGE_URL" 
      # $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
    - echo Build started on `date`
    - echo Building the Docker image...
    - docker build -t backend-flask . 
    - "docker tag $REPO_NAME $IMAGE_URL/$REPO_NAME"
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - "docker push $IMAGE_URL/$REPO_NAME"
      - echo "imagedefinitions.json > [{\"name\":\"$CONTAINER_NAME\",\"imageUri\":\"$IMAGE_URL/$REPO_NAME\"}]" > imagedefinitions.json
      - printf "[{\"name\":\"$CONTAINER_NAME\",\"imageUri\":\"$IMAGE_URL/$REPO_NAME\"}]" > imagedefinitions.json

env:
  variables:
    AWS_ACCOUNT_ID: 501753804709
    AWS_DEFAULT_REGION: us-east-1
    CONTAINER_NAME: backend-flask
    IMAGE_URL: 501753804709.dkr.ecr.us-east-1.amazonaws.com
    REPO_NAME: backend-flask-prod:latest
    AWS_COGNITO_USER_POOL_CLIENT_ID	: sc717ihfraldslskh4mvbn0ig
    AWS_COGNITO_USER_POOL_ID: us-east-1_bcDfPYEZg
    BACKEND_URL: "*"
    FRONTEND_URL: "*"
    OTEL_EXPORTER_OTLP_ENDPOINT: https://api.honeycomb.io
    OTEL_SERVICE_NAME: backend-flask
    AWS_RDS_POSTGRES_ENDPOINT: postgresql://root:pinata2023@cruddur-db-pinata.cfnkszftxohi.us-east-1.rds.amazonaws.com:5432/cruddur_pinata
  parameter-store:
    AWS_COGNITO_USER_POOL_CLIENT_ID: "/cruddur/backend-flask/AWS_ACCESS_KEY_ID"
    AWS_SECRET_ACCESS_KEY: "cruddur/backend-flask/AWS_SECRET_ACCESS_KEY"
    OTEL_EXPORTER_OTLP_HEADERS: cruddur/backend-flask/OTEL_EXPORTER_OTLP_HEADERS
    ROLLBAR_ACCESS_TOKEN: /cruddur/backend-flask/ROLLBAR_ACCESS_TOKEN
artifacts:
  files:
    - imagedefinitions.json